# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "732d2ec02110f4f5963377f87fcf7d2b"
name = "de-dial"
handle = "de-dial"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "quickstart-d1ede9e9.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "pubsub://dulce-engineering-433904:shopify"

[pos]
embedded = false
